# Generated by Django 5.0.4 on 2024-06-18 17:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("mytask", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="task",
            options={},
        ),
    ]
